### ISSUE TITLE
with Rim Light，the hair edge looks something wrong

### ISSUE THREAD

**Issue by miraclestar** [UnityTechnologies/HDRP-Defender-Character-Demo#1]
![image](https://user-images.githubusercontent.com/1502697/200722714-11b9cb7a-d0de-4f18-8721-d19ea6cbc1a9.png)
![image](https://user-images.githubusercontent.com/1502697/200722735-6f2d31ad-3764-4973-b21f-2bbf9285aa3c.png)

**Comment by michael430** [comment]
By default, you should get the rim effect as your upper picture which the lighting is from the back of the hair. I see their are no rim light from bottom picture, not sure if you changed any setting. Can you explain more in detail what's wrong
